### ISSUE TITLE
VM Vbox setup help

### ISSUE THREAD

**Issue by astroC86** [real-xinu/xkdb#7]
Do the same procedures apply for the virtual machine appliances setup provided on the [Purdue Website](https://xinu.cs.purdue.edu/) ? If not what steps could I look into to be able to get to get it to work?

**Comment by PaulkaToast** [comment]
This project is specifically for the xinu environment at Purdue. However, you could definitely reuse some of the components from here like the gdb stub, the way it would communicate with gdb would be different though.

**Comment by astroC86** [comment]
Could you please provide pointers as to one such way I could explore, to communicate between the VMs?, as I am hoping to make it available for myself and peers for our OS implementation Course. 

Thanks in advance
